### ISSUE TITLE
Checked button styles do not display correctly in Firefox

### ISSUE THREAD

**Issue by replete** [WebDevSimplified/react-todo-list#1]
Hi,

Thanks for sharing this tutorial, I just wanted to report a bug that is likely to trip up Firefox users.

I discovered presumably a CSS bug with the checkbox component in Firefox, the checkbox tick does not display correctly so visually it looks like the checkbox was not being checked. I initially wondered if this was one of those form component cross browser idiosyncracies, but with styles disabled you can see it is in fact checked.

![Screenshot 2023-04-18 at 10 15 21](https://user-images.githubusercontent.com/812139/232731843-0c24a091-5639-454c-8e27-744a266ce28a.png)

With styles disabled:
![Screenshot 2023-04-18 at 10 16 08](https://user-images.githubusercontent.com/812139/232732093-36579fee-86f7-47cf-bf21-41dc3e9f9185.png)

**Comment by mkhairavir** [comment]
having the same conditions.

**Comment by mkhairavir** [comment]
I also have the same condition on ubuntu firefox. I thought my code was an error, but when I try with Chrome browser all things run normally

**Comment by WebDevSimplified** [comment]
It looks like Firefox still hasn't implemented the :has selector in CSS. This is causing the bugs. You can manually enable to :has selector in Firefox or you can just use any other browser. They should implement :has soon, though.

**Comment by replete** [comment]
Thanks, Kyle.

No worries, not a problem for me just wanted to raise it as likely to trip up beginners. Firefox worldwide around 8%.
